
---
spring:
  jpa:
    generate-ddl: true
 
#US Region  
mongodb:
    testmessage: hello
    mongoNodes:
        - host: 40.69.174.18
          port: 27017
        - host: 52.176.148.254
          port: 27017
        - host: 52.173.33.218
          port: 27017            
    mongoNodeCredentials:
        - username: admin
          password: password
          authSource: admin